### ISSUE TITLE
Dealing with test fixtures.

### ISSUE THREAD

**Issue by blamarvt** [rackspace-titan/stacktester#20]
We have a lot of different cases to deal with here. From what I understand we're mostly of the opinion that tests are more concise and more meaningful when the environment is set to a certain state prior to test cases. This is expensive but provides the most accurate and repeatably successful test environment.

However, if we want to run this test suite against an existing environment, we shouldn't be attempting to execute nova-manage or other server-side tools because they might not exist on the older environment.

Proposal:

```
class StacktesterTestCase(unittest.TestCase):

    test_server_fixtures = []
    test_image_fixtures = []
    test_flavor_fixtures = []
    test_users = []

    def setUp(self):
        """Run before each test case.

        Ensure that all of the fixtures are set up and available via the API, and 
        that the given users are set up prior to each test being run. If the fixture
        already exists, don't delete and re-make, just leave it alone.

        """
        pass

    def tearDown(self):
        """Run after each test case.

        Do not remove fixtures here, as all fixture setup and destruction should
        happen during `setUp`.

        """
        pass
```

Yes? No? Thoughts?

**Comment by bcwaldon** [comment]
This is definitely a good direction to go. How do we deal with testing index calls if we don't fully control the list of entities that may be returned?

**Comment by throughnothing** [comment]
I like this a lot, and think we should avoid nova-manage calls and such as much as possible.  I assume this means we'll get rid of glance_client calls as well, and do all of that via the API.  Looks great to me, one thing that we can customize per-module/test-suite is using setUpClass, and setUpModule, if we want to limit the amount of full setups and teardowns we do where appropriate and acceptible.  Lookin good.

**Comment by markwash** [comment]
I was thinking of something similar. We could provide convenience methods in the stacktester library for things like setting up a specific server, image, etc. And then we could call them from setUpModule or setUpClass as appropriate. For example:

```
def setUpModule():
    stacktester.servers.setUpServers(test_servers)
    stacktester.images.clearImages()
```

I kind of like this better than getting the behavior for free from StacktesterTestCase because I will probably get confused at some point and go looking for how the fixtures are set up. When I do that with inheritance here I will be more confused until I realize that I have to go look at what the base class is doing. setUpModule is kind of confusing too but at least it is in the same file as the tests.

Not sure how you guys feel about that, maybe its not really any different.

**Comment by throughnothing** [comment]
I pretty much agree with what Mark said.  I really like that approach.
